const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const patient={name:'Asha Sharma',age:72,region:'Guwahati, Assam',caregiver:'Meera Sharma',relationship:'Daughter',language:'Assamese'};
const memories=[
{id:1,type:'Family',title:'Riya',detail:'Asha’s granddaughter. They celebrate birthdays together.',story:'Asha remembers Riya’s birthday celebrations and family evenings.',date:'12 Sep 2026',icon:'👧'},
{id:2,type:'Family',title:'Meera',detail:'Visits every morning and helps with medicines.',story:'Morning conversations with Meera are part of Asha’s daily rhythm.',date:'13 Sep 2026',icon:'👩'},
{id:3,type:'Place',title:'Dispur School',detail:'The school where Asha taught for many years.',story:'Asha spent many years teaching children in Dispur.',date:'08 Sep 2026',icon:'🏫'},
{id:4,type:'Place',title:'Family Home',detail:'The home where the family gathers during festivals.',story:'Family members gather here for food, stories and celebrations.',date:'10 Sep 2026',icon:'🏠'},
{id:5,type:'Routine',title:'Morning Tea',detail:'Tea → newspaper → garden walk.',story:'Asha starts the morning with tea, the newspaper and a short garden walk.',date:'14 Sep 2026',icon:'☕'},
{id:6,type:'Object',title:'Old Blue Car',detail:'A familiar family car used for outings.',story:'The blue car reminds Asha of family trips and market visits.',date:'09 Sep 2026',icon:'🚙'}
];
const reminders=[['09:00 AM','Take prescribed medicine','💊'],['10:30 AM','Drink water','💧'],['12:30 PM','Lunch','🍲'],['04:30 PM','One memory game','🧩'],['06:00 PM','Evening walk','🚶']];
let activities=[['Today','Identify the Person','Recognition','90%','Completed'],['Today','Memory by Picture','Recall','80%','Completed'],['Yesterday','Routine Recall','Sequencing','60%','Review']];
function toast(t){const e=$('#toast');if(!e)return;e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function speak(t){if(!('speechSynthesis'in window)){toast('Voice is not supported in this browser');return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.rate=.9;speechSynthesis.speak(u)}
function showPortal(role){const patientMode=role==='patient';$('#patientPortal').classList.toggle('active',patientMode);$('#caregiverPortal').classList.toggle('active',!patientMode);$$('.portal-btn').forEach(b=>b.classList.toggle('active',b.dataset.portal===role));showView(patientMode?'pHome':'cDashboard')}
function showView(id){const el=$('#'+id);if(!el)return;const portal=el.closest('.portal');portal.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v===el));portal.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===id));if(id==='pGames')renderGames();if(id==='pMemories')renderMemories();if(id==='pDay')renderRoutines();if(id==='cActivities')renderActivities();if(id==='cMemories')renderCaregiverMemories();window.scrollTo({top:0,behavior:'smooth'})}
function renderGames(){const box=$('#patientGames');if(!box)return;box.innerHTML=memories.map(m=>`<article class="game-card"><div class="game-top"><div class="game-icon">${m.icon}</div><div><span class="activity-type">PERSONALIZED • ${m.type}</span><h3>${m.type==='Family'?'Identify the Person':m.type==='Place'?'Where Is This?':m.type==='Routine'?'My Routine':m.type==='Object'?'My Familiar Object':'Memory Refinding'}</h3></div></div><p>Created from <b>${m.title}</b>, a familiar memory approved by the caregiver.</p><div class="game-meta"><span class="tag">Personal memory</span><span class="tag">Explainable</span></div><button class="btn btn-primary play" data-id="${m.id}">Play game</button></article>`).join('');$$('.play').forEach(b=>b.onclick=()=>playGame(+b.dataset.id))}
function playGame(id){const m=memories.find(x=>x.id===id);if(!m)return;const opts=[m.title,...memories.filter(x=>x.id!==id).slice(0,3).map(x=>x.title)];openModal(m.type==='Family'?'Identify the Person':'Personalized Memory Game',`<p><b>Which memory is connected to this activity?</b></p><div class="card"><div style="font-size:52px">${m.icon}</div><h3>${m.title}</h3><p>${m.detail}</p></div><div class="choices" style="display:grid;gap:8px;margin-top:12px">${opts.map(o=>`<button class="btn btn-soft choice" data-a="${o}">${o}</button>`).join('')}</div><p class="switcher-note">Cognitive engagement activity — not a diagnostic test.</p>`);$$('.choice').forEach(b=>b.onclick=()=>{const ok=b.dataset.a===m.title;activities.unshift(['Today',m.type==='Family'?'Identify the Person':'Memory Recall',m.type,ok?'100%':'50%',ok?'Completed':'Review']);closeModal();toast(ok?'Correct response recorded':'Response recorded — context retained');renderActivities()})}
function renderMemories(){const g=$('#patientMemoryGrid');if(!g)return;g.innerHTML=memories.map(m=>`<article class="card memory-card"><div class="memory-media">${m.icon}</div><div class="memory-body"><h3>${m.title}</h3><p>${m.story}</p><small>${m.type} • ${m.date}</small><div class="story-actions"><button class="btn btn-soft btn-small" data-story="${m.id}">Open story</button><button class="btn btn-ghost btn-small" data-listen="${m.id}">🔊 Listen</button></div></div></article>`).join('');$$('[data-story]').forEach(b=>b.onclick=()=>showStory(memories.find(m=>m.id==b.dataset.story)));$$('[data-listen]').forEach(b=>b.onclick=()=>{const m=memories.find(x=>x.id==b.dataset.listen);speak(m.story)}) ;showStory(memories[0])}
function showStory(m){const box=$('#patientStory');if(!box||!m)return;box.innerHTML=`<div class="story-media"><div style="height:100%;display:grid;place-items:center;font-size:90px">${m.icon}</div><div class="story-overlay"><b>${m.title}</b><span>${m.date} • ${m.type}</span></div></div><div class="story-actions"><button class="btn btn-soft" id="listenStory">🔊 Listen to story</button><button class="btn btn-ghost" id="nextStory">Next memory →</button></div>`;$('#listenStory').onclick=()=>speak(m.story);$('#nextStory').onclick=()=>showStory(memories[(memories.indexOf(m)+1)%memories.length])}
function renderRoutines(){const b=$('#patientRoutines');if(!b)return;b.innerHTML=reminders.map(r=>`<div class="routine"><div class="time">${r[0]}</div><div class="task-icon">${r[2]}</div><div class="routine-main"><b>${r[1]}</b><small>Caregiver reminder</small></div></div>`).join('')}
function renderActivities(){const t=$('#activityTable');if(!t)return;t.innerHTML=activities.slice(0,12).map(a=>`<tr>${a.map((x,i)=>`<td>${i===4?`<span class="status-pill ${x==='Completed'?'status-good':'status-review'}">${x}</span>`:x}</td>`).join('')}</tr>`).join('')}
function renderCaregiverMemories(){const g=$('#caregiverMemoryList');if(!g)return;g.innerHTML=memories.map(m=>`<div class="info-row"><span>${m.icon} ${m.title}</span><b>${m.type}</b></div>`).join('')}
function openModal(title,body){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=body;$('#modal').classList.add('open')}
function closeModal(){$('#modal').classList.remove('open')}
function init(){
 $('#enterBtn').onclick=()=>{$('#welcome').classList.add('hidden');$('#roles').classList.remove('hidden')};
 $$('[data-role]').forEach(b=>b.onclick=()=>{$('#boot').classList.add('hidden');showPortal(b.dataset.role)});
 $$('[data-portal]').forEach(b=>b.onclick=()=>showPortal(b.dataset.portal));
 $$('.nav').forEach(b=>b.onclick=()=>showView(b.dataset.view));
 $$('[data-goto]').forEach(b=>b.onclick=()=>showView(b.dataset.goto));
 $('#closeModal').onclick=closeModal;$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};
 $('#voiceBtn').onclick=()=>speak(`Good morning ${patient.name}. You have ${reminders.length} reminders and personalized memory activities.`);
 $('#readRoutine').onclick=()=>speak('Today: '+reminders.map(r=>r[0]+' '+r[1]).join('. '));
 $('#profileBtn').onclick=()=>openModal('Profile',`<p><b>${patient.name}</b><br>${patient.age} years • ${patient.region}</p><p>Caregiver: ${patient.caregiver}<br>Relationship: ${patient.relationship}<br>Language: ${patient.language}</p>`);
 $('#patientCompanion').onclick=()=>openModal('NeuroSathi Voice Companion','<p>Ask me to read your day or open your games.</p><div class="modal-actions"><button class="btn btn-soft" id="compRead">🔊 Read my day</button><button class="btn btn-primary" id="compGames">🧩 Open games</button></div>');
 $('#journalSend').onclick=()=>{const i=$('#journalInput');if(i&&i.value.trim()){const c=$('#chat');c.insertAdjacentHTML('beforeend',`<div class="bubble me">${i.value.replace(/[<>]/g,'')}</div><div class="bubble ai">Thank you. I saved that as today's story for your caregiver.</div>`);i.value='';toast('Journal saved')}};
 $('#journalVoice').onclick=()=>{const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){toast('Voice input is not supported here');return}const r=new SR();r.lang='en-IN';r.onresult=e=>{$('#journalInput').value=e.results[0][0].transcript};r.start()};
 $('#patientAddMemory').onclick=()=>showPortal('caregiver');
 renderGames();renderMemories();renderRoutines();renderActivities();renderCaregiverMemories();
 let slide=0;setInterval(()=>{const s=$('#homeSlides'),d=$('#homeDots');if(!s||!d)return;slide=(slide+1)%3;s.style.transform=`translateX(-${slide*100}%)`;[...d.children].forEach((x,i)=>x.classList.toggle('active',i===slide))},4200);
 $('#boot').classList.remove('hidden');
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();